/**
 * 乒乓球器材数据库 —— 底板 / 胶皮
 *
 * 数值口径说明（重要）：
 *   speed / spin / control / hard 均为 0-100 的「横向可比指数」，由公开评测与
 *   厂商定位换算而来，用于同站内不同器材之间的相对比较。
 *   各厂商官方刻度互不通用（蝴蝶自己的刻度、德系 47.5°、红双喜 39 度是四套体系），
 *   所以这里统一归一化，不直接引用任何一家的官方数字。
 */

/* ---------- 木材与纤维 ---------- */
const PLY = {
  limba:  { n: '林巴',      c: '#c8975a', r: 0.72 },
  ayous:  { n: '阿尤斯',    c: '#e0b276', r: 0.70 },
  kiri:   { n: '桐木',      c: '#d9b077', r: 0.68 },
  hinoki: { n: '桧木',      c: '#e3c48d', r: 0.66 },
  walnut: { n: '胡桃',      c: '#8a5a34', r: 0.74 },
  rose:   { n: '玫瑰木',    c: '#7a4a2e', r: 0.76 },
  ebony:  { n: '黑檀',      c: '#3a2a22', r: 0.78 },
  alc:    { n: 'ALC 芳碳',  c: '#2c3a4a', r: 0.38 },
  zlc:    { n: 'ZLC 纤维',  c: '#2a2d31', r: 0.34 },
  szlc:   { n: 'Super ZLC', c: '#1e2124', r: 0.30 },
  zlf:    { n: 'ZL 纤维',   c: '#3b3f45', r: 0.40 },
  carbon: { n: '碳素',      c: '#23262b', r: 0.30 },
};

/* ---------- 典型层压结构（从正面到背面，单位 mm） ---------- */
const STRUCT = {
  // 5 层纯木
  w5:     [['limba', 0.55], ['ayous', 1.05], ['kiri', 2.6], ['ayous', 1.05], ['limba', 0.55]],
  // 7 层纯木
  w7:     [['limba', 0.55], ['ayous', 0.85], ['kiri', 0.9], ['ayous', 1.3], ['kiri', 0.9], ['ayous', 0.85], ['limba', 0.55]],
  // 纤维层统一按 0.22mm。这是「纤维 + 浸渍树脂」的复合层厚度，
  // 比单看纤维布厚一点，但这样在 1:1 尺度下才看得见那道深色线 —— 0.15mm 只有 3~4 像素，等于没做。
  // 5+2 外置芳碳
  alcOut: [['limba', 0.55], ['alc', 0.22], ['ayous', 0.9], ['kiri', 2.6], ['ayous', 0.9], ['alc', 0.22], ['limba', 0.55]],
  // 5+2 内置芳碳
  alcIn:  [['limba', 0.6], ['ayous', 1.0], ['alc', 0.22], ['kiri', 2.3], ['alc', 0.22], ['ayous', 1.0], ['limba', 0.6]],
  // 5+2 外置 ZLC
  zlcOut: [['limba', 0.55], ['zlc', 0.22], ['ayous', 0.9], ['kiri', 2.6], ['ayous', 0.9], ['zlc', 0.22], ['limba', 0.55]],
  // 5+2 内置 ZLC
  zlcIn:  [['limba', 0.6], ['ayous', 1.0], ['zlc', 0.22], ['kiri', 2.3], ['zlc', 0.22], ['ayous', 1.0], ['limba', 0.6]],
  // 5+2 Super ZLC
  szlcOut:[['limba', 0.55], ['szlc', 0.22], ['ayous', 0.9], ['kiri', 2.6], ['ayous', 0.9], ['szlc', 0.22], ['limba', 0.55]],
  // 5+2 ZL 纤维（无碳，软弹）
  zlfOut: [['limba', 0.55], ['zlf', 0.25], ['ayous', 0.9], ['kiri', 2.6], ['ayous', 0.9], ['zlf', 0.25], ['limba', 0.55]],
  // 3+2 碳素（桧木面材，厚大芯）
  c3x2:   [['hinoki', 1.0], ['carbon', 0.28], ['kiri', 3.1], ['carbon', 0.28], ['hinoki', 1.0]],
  // 7 层硬木（黑檀/玫瑰面材）
  hw7:    [['ebony', 0.6], ['ayous', 0.9], ['kiri', 1.1], ['ayous', 1.0], ['kiri', 1.1], ['ayous', 0.9], ['ebony', 0.6]],
  // 5+2 碳素（外置）
  cOut:   [['limba', 0.55], ['carbon', 0.2], ['ayous', 0.9], ['kiri', 2.5], ['ayous', 0.9], ['carbon', 0.2], ['limba', 0.55]],
};

/** 把结构表展开成实际层厚（按目标总厚等比缩放） */
export function pliesOf(blade) {
  const src = STRUCT[blade.struct];
  const sum = src.reduce((a, p) => a + p[1], 0);
  const k = blade.thickness / sum;
  return src.map(([key, t]) => ({ ...PLY[key], t: +(t * k).toFixed(3) }));
}

/* ---------- 手柄配色 ---------- */
const H = (base, grain, stripe) => ({ base, grain, stripe });

/* ---------- 底板 ---------- */
export const BLADES = [
  /* ===== 蝴蝶 Butterfly ===== */
  { id: 'viscaria', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Viscaria', cn: '维斯卡利亚',
    struct: 'alcOut', thickness: 5.8, speed: 88, spin: 76, control: 82, hard: 62, weight: 87,
    handle: H('#4b3a2e', '#2c2118', '#141414'), price: 1280, tag: '经典外置芳碳',
    note: '外置芳碳的标杆。出球干脆、弧线低平，中远台相持稳定，从入门到专业都能打。' },
  { id: 'boll-alc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Timo Boll ALC', cn: '波尔 ALC',
    struct: 'alcOut', thickness: 5.8, speed: 86, spin: 78, control: 84, hard: 58, weight: 86,
    handle: H('#d9c49a', '#a8875a', '#1b2a3a'), price: 1180, tag: '波尔同款',
    note: '比 Viscaria 稍软，持球感更好，弧圈上台率高，全面型选手的万金油。' },
  { id: 'boll-spirit', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Timo Boll Spirit', cn: '波尔精神',
    struct: 'alcOut', thickness: 5.7, speed: 85, spin: 79, control: 85, hard: 56, weight: 85,
    handle: H('#dcc79e', '#a8875a', '#233246'), price: 1080, tag: '',
    note: 'ALC 的初代经典型号，手感通透，弹性温和，适合以旋转为主的打法。' },
  { id: 'boll-zlc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Timo Boll ZLC', cn: '波尔 ZLC',
    struct: 'zlcOut', thickness: 5.6, speed: 92, spin: 78, control: 79, hard: 68, weight: 84,
    handle: H('#dcc79e', '#a8875a', '#4a2f2f'), price: 1580, tag: '',
    note: 'ZLC 纤维回弹更快，甜区大，借力出色，中近台抢攻犀利。' },
  { id: 'boll-zlf', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Timo Boll ZLF', cn: '波尔 ZLF',
    struct: 'zlfOut', thickness: 5.7, speed: 82, spin: 82, control: 88, hard: 50, weight: 83,
    handle: H('#dcc79e', '#a8875a', '#2f4a3a'), price: 1480, tag: '软弹持球',
    note: '不含碳的 ZL 纤维，形变明显、吃球深，旋转极佳但需要主动发力。' },
  { id: 'zjk-alc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Zhang Jike ALC', cn: '张继科 ALC',
    struct: 'alcOut', thickness: 5.8, speed: 89, spin: 77, control: 81, hard: 63, weight: 88,
    handle: H('#1f1f22', '#3a3a3e', '#8a1f2a'), price: 1280, tag: '张继科同款',
    note: '在 Viscaria 基础上略增刚性，大力爆冲的支撑更好，偏进攻型。' },
  { id: 'zjk-zlc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Zhang Jike ZLC', cn: '张继科 ZLC',
    struct: 'zlcOut', thickness: 5.6, speed: 93, spin: 76, control: 78, hard: 70, weight: 85,
    handle: H('#1f1f22', '#3a3a3e', '#b08a2a'), price: 1680, tag: '',
    note: '刚性更强、出球更快，适合力量充足的近台快弧打法。' },
  { id: 'zjk-szlc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Zhang Jike Super ZLC', cn: '张继科 Super ZLC',
    struct: 'szlcOut', thickness: 5.6, speed: 97, spin: 74, control: 74, hard: 78, weight: 86,
    handle: H('#141416', '#33333a', '#c0a24a'), price: 2380, tag: '旗舰',
    note: '蝴蝶最刚猛的纤维结构，甜区极大。脱板极快，对发力与手感要求高。' },
  { id: 'fzd-alc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Fan Zhendong ALC', cn: '樊振东 ALC',
    struct: 'alcOut', thickness: 5.8, speed: 90, spin: 77, control: 81, hard: 64, weight: 88,
    handle: H('#2a2a2e', '#454549', '#1f4a8a'), price: 1380, tag: '樊振东同款',
    note: '外置芳碳加强版，出球速度与稳定性的平衡点抓得很好，暴力弧圈利器。' },
  { id: 'fzd-zlc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Fan Zhendong ZLC', cn: '樊振东 ZLC',
    struct: 'zlcOut', thickness: 5.6, speed: 94, spin: 76, control: 78, hard: 71, weight: 86,
    handle: H('#2a2a2e', '#454549', '#8a1f2a'), price: 1780, tag: '',
    note: '更硬的纤维层，中远台对拉力量衰减小，适合高强度相持。' },
  { id: 'harimoto-alc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Harimoto Tomokazu ALC', cn: '张本智和 ALC',
    struct: 'alcIn', thickness: 5.9, speed: 85, spin: 82, control: 87, hard: 54, weight: 89,
    handle: H('#c8a878', '#8f6f42', '#1f3a6a'), price: 1380, tag: '张本智和同款',
    note: '内置芳碳，碳层贴近大芯，吃球深、形变柔和，近台反手拧拉的容错极高。' },
  { id: 'harimoto-inner', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Harimoto Tomokazu Innerforce ALC', cn: '张本智和 Innerforce ALC',
    struct: 'alcIn', thickness: 5.9, speed: 83, spin: 83, control: 89, hard: 51, weight: 88,
    handle: H('#c8a878', '#8f6f42', '#4a2f6a'), price: 1280, tag: '',
    note: 'Innerforce 结构，手感绵密，防守与反攻的转换非常顺滑。' },
  { id: 'harimoto-zlc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Harimoto Tomokazu ZLC', cn: '张本智和 ZLC',
    struct: 'zlcIn', thickness: 5.8, speed: 89, spin: 82, control: 84, hard: 60, weight: 87,
    handle: H('#c8a878', '#8f6f42', '#1f6a5a'), price: 1780, tag: '',
    note: '内置 ZLC，兼具形变吃球与纤维回弹，中台拉球质量高。' },
  { id: 'innerforce-alc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Innerforce Layer ALC', cn: '内置 ALC',
    struct: 'alcIn', thickness: 5.9, speed: 84, spin: 82, control: 88, hard: 52, weight: 87,
    handle: H('#c8a878', '#8f6f42', '#2f4a3a'), price: 1180, tag: '内置手感',
    note: '内置结构代表作。中小力量下形变充分，越发力越有底劲，弧圈打法友好。' },
  { id: 'innerforce-zlc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Innerforce Layer ZLC', cn: '内置 ZLC',
    struct: 'zlcIn', thickness: 5.8, speed: 88, spin: 83, control: 85, hard: 58, weight: 85,
    handle: H('#c8a878', '#8f6f42', '#6a2f3a'), price: 1580, tag: '',
    note: '内置 ZLC，比内置 ALC 更快一档，同时保留吃球感。' },
  { id: 'korbel', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Korbel', cn: '科贝尔',
    struct: 'w5', thickness: 5.9, speed: 74, spin: 80, control: 90, hard: 44, weight: 88,
    handle: H('#8a5f38', '#5c3d22', '#3a2614'), price: 780, tag: '纯木经典',
    note: '五层纯木的教科书。手感清晰、控制一流，练球与比赛通吃，性价比极高。' },
  { id: 'korbel-sk7', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Korbel SK7', cn: '科贝尔 SK7',
    struct: 'w7', thickness: 6.7, speed: 82, spin: 76, control: 84, hard: 62, weight: 92,
    handle: H('#8a5f38', '#5c3d22', '#2a2a2a'), price: 880, tag: '七层纯木',
    note: '七层纯木，底板刚性强，中近台快攻与快带的速度优势明显。' },
  { id: 'primorac', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Primorac', cn: '普里莫拉茨',
    struct: 'w5', thickness: 5.8, speed: 72, spin: 79, control: 91, hard: 42, weight: 85,
    handle: H('#c8a878', '#8f6f42', '#3a3a3a'), price: 680, tag: '入门首选',
    note: '入门与进阶的公认推荐。容错高、好上手，配两面入门胶皮即可打很多年。' },
  { id: 'maze', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Maze', cn: '梅兹',
    struct: 'alcOut', thickness: 5.7, speed: 84, spin: 80, control: 86, hard: 55, weight: 86,
    handle: H('#b8b0a0', '#8a8070', '#1f1f1f'), price: 1180, tag: '',
    note: '外置芳碳中手感偏柔的一支，弧线饱满，过渡球质量高。' },
  { id: 'schlager-carbon', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Schlager Carbon', cn: '施拉格碳素',
    struct: 'c3x2', thickness: 6.0, speed: 95, spin: 72, control: 74, hard: 76, weight: 90,
    handle: H('#1a1a1c', '#3a3a3e', '#8a6a1f'), price: 1480, tag: '暴力代表',
    note: '三木两碳、桧木面材。出球极快，是快攻与暴力弧圈的经典选择。' },
  { id: 'amultart', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Amultart', cn: '阿姆塔特',
    struct: 'szlcOut', thickness: 5.8, speed: 96, spin: 75, control: 76, hard: 74, weight: 88,
    handle: H('#2a1f1a', '#4a382c', '#b08a2a'), price: 2180, tag: '',
    note: '桧木面材 + Super ZLC，形变与回弹兼备，中远台的力量储备惊人。' },
  { id: 'photino', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Photino', cn: '光子',
    struct: 'zlfOut', thickness: 5.8, speed: 86, spin: 80, control: 84, hard: 58, weight: 87,
    handle: H('#c0b8a8', '#8a8070', '#3a4a6a'), price: 1680, tag: '',
    note: '桧木 + ZL 纤维，手感酥脆，弹击与快带的手感反馈非常直接。' },
  { id: 'ovtcharov-tc', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Ovtcharov True Carbon', cn: '奥恰洛夫 真碳',
    struct: 'cOut', thickness: 5.8, speed: 90, spin: 76, control: 80, hard: 67, weight: 88,
    handle: H('#1f2a3a', '#3a4a5e', '#c0c0c0'), price: 1280, tag: '',
    note: '外置碳素，刚柔并济，中台反手对拉的速度与稳定性兼顾。' },
  { id: 'kong-linghui', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Kong Linghui', cn: '孔令辉',
    struct: 'w5', thickness: 5.7, speed: 70, spin: 80, control: 92, hard: 40, weight: 84,
    handle: H('#8a5f38', '#5c3d22', '#2f4a8a'), price: 880, tag: '',
    note: '经典五夹，软而弹，近台快攻与台内小球的手感极佳。' },
  { id: 'sk7-classic', brand: 'Butterfly', brandCn: '蝴蝶', name: 'SK7 Classic', cn: 'SK7 经典',
    struct: 'w7', thickness: 6.8, speed: 84, spin: 74, control: 83, hard: 65, weight: 93,
    handle: H('#8a5f38', '#5c3d22', '#1f1f1f'), price: 920, tag: '',
    note: '七层纯木快攻板，支撑扎实，打颗粒胶特别好使。' },
  { id: 'hadraw-5', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Hadraw 5', cn: '榉木五层',
    struct: 'w5', thickness: 5.9, speed: 76, spin: 79, control: 89, hard: 48, weight: 86,
    handle: H('#c8a878', '#8f6f42', '#4a3a2a'), price: 880, tag: '',
    note: '硬木面材的五夹，速度比科贝尔再快一点，同时保留纯木的清晰手感。' },
  { id: 'hadraw-vr', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Hadraw VR', cn: '硬木 VR',
    struct: 'w7', thickness: 6.4, speed: 83, spin: 76, control: 84, hard: 62, weight: 85,
    handle: H('#c8a878', '#8f6f42', '#6a2f2f'), price: 980, tag: '',
    note: '七层硬木，兼顾速度与手感，适合中近台两面弧圈。' },

  /* ===== 其他主流品牌 ===== */
  { id: 'hl5', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane Long 5', cn: '狂飙龙 5',
    struct: 'alcIn', thickness: 5.9, speed: 87, spin: 84, control: 85, hard: 56, weight: 89,
    handle: H('#8a6a3a', '#5c4526', '#8a1f2a'), price: 1580, tag: '马龙 / 王楚钦同款',
    note: '国家队主力板。内置芳碳配狂飙，吃球深、底劲足，正手弧圈质量顶级。' },
  { id: 'hl5x', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane Long 5X', cn: '狂飙龙 5X',
    struct: 'alcIn', thickness: 6.0, speed: 89, spin: 83, control: 84, hard: 60, weight: 88,
    handle: H('#8a6a3a', '#5c4526', '#1f3a6a'), price: 1680, tag: '',
    note: '龙 5 的加硬版本，纤维层更厚，中远台对拉的力量更足。' },
  { id: 'hl3', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane Long 3', cn: '狂飙龙 3',
    struct: 'alcIn', thickness: 5.8, speed: 83, spin: 84, control: 88, hard: 50, weight: 88,
    handle: H('#8a6a3a', '#5c4526', '#2f6a4a'), price: 1280, tag: '',
    note: '比龙 5 更软更持球，形变充分，适合以旋转和落点为主的弧圈打法。' },
  { id: 'fangbo-carbon', brand: 'DHS', brandCn: '红双喜', name: 'Fang Bo Carbon', cn: '方博碳素',
    struct: 'cOut', thickness: 5.9, speed: 88, spin: 78, control: 82, hard: 64, weight: 87,
    handle: H('#6a4a2a', '#43301a', '#c0a24a'), price: 980, tag: '',
    note: '外置碳素，刚性充足，中近台抢攻与反手弹击很有威胁。' },
  { id: 'hao2', brand: 'DHS', brandCn: '红双喜', name: 'Hao 2', cn: '皓 2',
    struct: 'w5', thickness: 5.8, speed: 78, spin: 82, control: 88, hard: 50, weight: 85,
    handle: H('#8a6a3a', '#5c4526', '#1f1f1f'), price: 1180, tag: '',
    note: '为王皓设计的五夹，横打手感顺滑，直板横打选手的经典配置。' },
  { id: 'ebenholz7', brand: 'Stiga', brandCn: '斯帝卡', name: 'Ebenholz VII', cn: '黑檀 7',
    struct: 'hw7', thickness: 6.4, speed: 92, spin: 78, control: 80, hard: 74, weight: 95,
    handle: H('#2a1f18', '#4a382c', '#b08a2a'), price: 1480, tag: '硬木七夹',
    note: '黑檀面材，出球快而扎实。中近台强攻型，需要较好的发力基础。' },
  { id: 'rosewood7', brand: 'Stiga', brandCn: '斯帝卡', name: 'Rosewood VII', cn: '玫瑰 7',
    struct: 'hw7', thickness: 6.3, speed: 90, spin: 80, control: 81, hard: 70, weight: 92,
    handle: H('#5c2f1f', '#3a1c12', '#c0a24a'), price: 1380, tag: '',
    note: '玫瑰木面材，比黑檀稍柔，旋转与速度的平衡更好，弧圈快攻通吃。' },
  { id: 'clipper', brand: 'Stiga', brandCn: '斯帝卡', name: 'Clipper Wood', cn: 'CL 快速木',
    struct: 'w7', thickness: 6.6, speed: 83, spin: 76, control: 85, hard: 63, weight: 90,
    handle: H('#a87a4a', '#7a5432', '#1f1f1f'), price: 880, tag: '颗粒神器',
    note: '经典七层纯木，支撑扎实、形变小，打正胶生胶的公认首选之一。' },
  { id: 'carbo76', brand: 'Stiga', brandCn: '斯帝卡', name: 'Carbo 7.6', cn: '红黑碳王',
    struct: 'cOut', thickness: 6.2, speed: 91, spin: 77, control: 80, hard: 69, weight: 88,
    handle: H('#1a1a1c', '#3a3a3e', '#8a1f2a'), price: 1080, tag: '',
    note: '碳素 + 七层结构，出球快、弧线低，快弧打法的老牌利器。' },
  { id: 'acoustic', brand: 'Nittaku', brandCn: '尼塔库', name: 'Acoustic', cn: '木吉他',
    struct: 'w5', thickness: 5.9, speed: 79, spin: 83, control: 90, hard: 46, weight: 85,
    handle: H('#d9c49a', '#a8875a', '#3a2a1a'), price: 1280, tag: '手感标杆',
    note: '以手感细腻著称的五夹，形变线性度极好，弧圈上台率与球质兼备。' },
  { id: 'violin', brand: 'Nittaku', brandCn: '尼塔库', name: 'Violin', cn: '小提琴',
    struct: 'w5', thickness: 5.9, speed: 81, spin: 82, control: 89, hard: 49, weight: 86,
    handle: H('#c8a878', '#8f6f42', '#4a2f1f'), price: 1380, tag: '',
    note: '木吉他的姐妹型号，略硬一点，出球更挺，兼顾速度与手感。' },
  { id: 'latika', brand: 'Nittaku', brandCn: '尼塔库', name: 'Latika', cn: '拉特',
    struct: 'w5', thickness: 5.7, speed: 74, spin: 82, control: 91, hard: 42, weight: 84,
    handle: H('#d9c49a', '#a8875a', '#6a4a2a'), price: 880, tag: '',
    note: '柔和易控的五夹，适合初学者与以控制为主的打法。' },
  { id: 'malin-carbon', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Ma Lin Carbon', cn: '马琳碳素',
    struct: 'cOut', thickness: 5.9, speed: 87, spin: 79, control: 83, hard: 62, weight: 85,
    handle: H('#8a5f38', '#5c3d22', '#1f1f1f'), price: 980, tag: '马琳同款',
    note: '为马琳打造的直板碳素，台内小球手感清晰，正手爆冲支撑十足。' },
  { id: 'yeo', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Extra Offensive', cn: 'YEO 马琳',
    struct: 'w5', thickness: 5.9, speed: 80, spin: 82, control: 87, hard: 52, weight: 88,
    handle: H('#a87a4a', '#7a5432', '#2f4a8a'), price: 880, tag: '直板经典',
    note: '硬木面材五夹，直板快攻弧圈的经典选择，推挡与横打都很顺手。' },
  { id: 'force-pro', brand: 'Tibhar', brandCn: '挺拔', name: 'Samsonov Force Pro Black', cn: '无字黑萨',
    struct: 'w7', thickness: 6.5, speed: 85, spin: 78, control: 84, hard: 64, weight: 87,
    handle: H('#1a1a1c', '#3a3a3e', '#c0c0c0'), price: 880, tag: '',
    note: '七层纯木，力量与控制的平衡出色，欧洲选手偏爱的全面型底板。' },
  { id: 'stratus-pw', brand: 'Tibhar', brandCn: '挺拔', name: 'Stratus Power Wood', cn: '斯特拉图',
    struct: 'w5', thickness: 5.9, speed: 77, spin: 80, control: 88, hard: 50, weight: 85,
    handle: H('#c9a06a', '#8a6236', '#4a5a6a'), price: 680, tag: '',
    note: '偏软的五夹，形变好、容错高，配德系套胶上手非常舒服。' },
];

/* ---------- 胶皮 ---------- */
export const RUBBER_TYPES = {
  inv:  { cn: '反胶', en: 'Inverted', pips: null },
  sp:   { cn: '正胶', en: 'Short Pips', pips: { r: 1.05, h: 0.85, gap: 3.15 } },
  mp:   { cn: '生胶', en: 'Medium Pips', pips: { r: 0.92, h: 1.15, gap: 3.35 } },
  lp:   { cn: '长胶', en: 'Long Pips', pips: { r: 0.72, h: 1.95, gap: 3.6 } },
  anti: { cn: '防弧', en: 'Anti-Spin', pips: null },
};

export const RUBBER_COLORS = {
  black:  { cn: '黑', hex: '#17191d' },
  red:    { cn: '红', hex: '#b8232f' },
  blue:   { cn: '蓝', hex: '#1f5fbf' },
  pink:   { cn: '粉', hex: '#dd5f86' },
  green:  { cn: '绿', hex: '#1c8a5c' },
  violet: { cn: '紫', hex: '#6a4bbf' },
};

/* 海绵色板 */
const SP = {
  tenergy: '#e6a03c', dignics: '#dd7a48', dhs: '#df6229', dhsBlue: '#2f6fb5',
  esn: '#efe1c2', esnBlue: '#3b6ea8', pink: '#e5a09a', grey: '#8e8b84',
};

export const RUBBERS = [
  /* ===== 蝴蝶 Butterfly ===== */
  { id: 'tenergy05', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Tenergy 05', cn: '泰纳吉 05',
    type: 'inv', hard: 52, hardLabel: '36°', speed: 91, spin: 97, control: 82, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 47, price: 780, tag: '旋转旗舰',
    note: '高摩擦面胶 + 弹簧海绵，弧线高、二跳下扎。近台拧拉与弧圈的天花板级选择。' },
  { id: 'tenergy05fx', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Tenergy 05 FX', cn: '泰纳吉 05 FX',
    type: 'inv', hard: 40, hardLabel: '32°', speed: 85, spin: 94, control: 89, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 44, price: 780, tag: '',
    note: '05 的软海绵版。持球时间更长、更容易起下旋，反手与力量偏小的选手友好。' },
  { id: 'tenergy64', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Tenergy 64', cn: '泰纳吉 64',
    type: 'inv', hard: 50, hardLabel: '35°', speed: 95, spin: 90, control: 80, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 47, price: 780, tag: '',
    note: '颗粒更长更疏，出球速度最快的一支。适合近台快攻与反手弹击。' },
  { id: 'tenergy80', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Tenergy 80', cn: '泰纳吉 80',
    type: 'inv', hard: 51, hardLabel: '35°', speed: 93, spin: 93, control: 84, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 47, price: 780, tag: '均衡',
    note: '介于 05 与 64 之间，旋转与速度都不偏科，万金油套胶。' },
  { id: 'tenergy25', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Tenergy 25', cn: '泰纳吉 25',
    type: 'inv', hard: 53, hardLabel: '36°', speed: 90, spin: 88, control: 82, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 47, price: 780, tag: '',
    note: '颗粒最粗最密，撞击感直接，适合以击打为主的近台快攻。' },
  { id: 'dignics05', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Dignics 05', cn: '迪格尼克斯 05',
    type: 'inv', hard: 58, hardLabel: '40°', speed: 94, spin: 96, control: 88, tacky: false,
    sponge: SP.dignics, colors: ['black', 'red'], weight: 48, price: 880, tag: '新一代旗舰',
    note: 'Spring Sponge X 海绵，旋转与速度同时提升，相持中的稳定性明显优于 Tenergy。' },
  { id: 'dignics09c', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Dignics 09C', cn: '迪格尼克斯 09C',
    type: 'inv', hard: 60, hardLabel: '44°', speed: 90, spin: 99, control: 90, tacky: true,
    sponge: SP.dignics, colors: ['black', 'red'], weight: 49, price: 880, tag: '粘性',
    note: '蝴蝶唯一的粘性面胶旗舰。发球与摆短的旋转极强，张本智和正手在用。' },
  { id: 'dignics64', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Dignics 64', cn: '迪格尼克斯 64',
    type: 'inv', hard: 56, hardLabel: '40°', speed: 97, spin: 91, control: 86, tacky: false,
    sponge: SP.dignics, colors: ['black', 'red'], weight: 48, price: 880, tag: '',
    note: 'Dignics 系列中出球最快的一支，反手弹击与快撕的威胁极大。' },
  { id: 'dignics80', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Dignics 80', cn: '迪格尼克斯 80',
    type: 'inv', hard: 57, hardLabel: '40°', speed: 95, spin: 94, control: 88, tacky: false,
    sponge: SP.dignics, colors: ['black', 'red'], weight: 48, price: 880, tag: '',
    note: '05 与 64 的折中，兼顾旋转与速度，正反手都能用。' },
  { id: 'glayzer09c', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Glayzer 09C', cn: '格雷泽 09C',
    type: 'inv', hard: 54, hardLabel: '42°', speed: 86, spin: 93, control: 90, tacky: true,
    sponge: SP.dignics, colors: ['black', 'red'], weight: 46, price: 480, tag: '高性价比粘性',
    note: '09C 的平价版本，粘性面胶保留，旋转依旧出色，价格只有旗舰的一半。' },
  { id: 'glayzer', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Glayzer', cn: '格雷泽',
    type: 'inv', hard: 50, hardLabel: '38°', speed: 88, spin: 90, control: 88, tacky: false,
    sponge: SP.dignics, colors: ['black', 'red'], weight: 45, price: 380, tag: '',
    note: '入门到进阶的甜点套胶，旋转接近高端型号，容错很高。' },
  { id: 'rozena', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Rozena', cn: '罗泽娜',
    type: 'inv', hard: 44, hardLabel: '34°', speed: 84, spin: 85, control: 90, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 43, price: 330, tag: '入门推荐',
    note: 'Tenergy 的入门版，海绵软、容错高，练球阶段最好的选择之一。' },
  { id: 'sriver', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Sriver', cn: '斯瑞沃',
    type: 'inv', hard: 46, hardLabel: '35°', speed: 76, spin: 78, control: 92, tacky: false,
    sponge: SP.grey, colors: ['black', 'red'], weight: 42, price: 280, tag: '经典',
    note: '几代人的启蒙套胶。速度不快但控制极佳，练基本功的绝佳搭档。' },
  { id: 'bryce-hs', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Bryce Highspeed', cn: '布莱斯 高速',
    type: 'inv', hard: 55, hardLabel: '38°', speed: 94, spin: 86, control: 78, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 46, price: 480, tag: '',
    note: '传统高速套胶的代表，脱板极快，适合近台快攻与借力打法。' },
  { id: 'roundell', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Roundell', cn: '圆舞曲',
    type: 'inv', hard: 47, hardLabel: '36°', speed: 80, spin: 82, control: 92, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 44, price: 420, tag: '',
    note: '以稳定著称的套胶，弧线高、失误少，适合以相持和控制为主的打法。' },
  { id: 'impartial-xb', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Impartial XB', cn: '英帕修 XB',
    type: 'sp', hard: 48, hardLabel: '35°', speed: 84, spin: 72, control: 90, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 42, price: 420, tag: '',
    note: '正胶。颗粒密集、速度直接，近台快攻与快带的下沉感明显。' },
  { id: 'impartial-xs', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Impartial XS', cn: '英帕修 XS',
    type: 'mp', hard: 46, hardLabel: '34°', speed: 82, spin: 70, control: 89, tacky: false,
    sponge: SP.tenergy, colors: ['black', 'red'], weight: 41, price: 420, tag: '',
    note: '生胶。回球下沉、弧线飘忽，接发球与相持中的节奏变化利器。' },
  { id: 'feint-long3', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Feint Long III', cn: '费恩特 长胶 III',
    type: 'lp', hard: 38, hardLabel: '30°', speed: 55, spin: 62, control: 88, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 33, price: 460, tag: '',
    note: '长胶。削球与倒板打法的主力，能把上旋变成下旋，回球极不规则。' },
  { id: 'feint-soft', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Feint Soft', cn: '费恩特 软',
    type: 'lp', hard: 35, hardLabel: '28°', speed: 52, spin: 60, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 32, price: 420, tag: '',
    note: '海绵更软的长胶，控球更容易，适合刚转削球或防守型打法的选手。' },
  { id: 'challenger-attic', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Challenger Attic', cn: '查伦者 防弧',
    type: 'anti', hard: 42, hardLabel: '33°', speed: 60, spin: 40, control: 94, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 38, price: 420, tag: '',
    note: '防弧胶。几乎不吃旋转，能把对手的强旋转球"卸"成不转，防守反击的奇兵。' },
  { id: 'orthodox', brand: 'Butterfly', brandCn: '蝴蝶', name: 'Orthodox', cn: '奥索多克斯',
    type: 'sp', hard: 44, hardLabel: '33°', speed: 80, spin: 74, control: 92, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 41, price: 380, tag: '',
    note: '正胶。控制优先的设计，台内小球与快攻都很稳，颗粒打法的入门好选择。' },

  /* ===== 红双喜 DHS ===== */
  { id: 'h3-national', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane 3 National', cn: '狂飙三 国狂',
    type: 'inv', hard: 82, hardLabel: '41 度', speed: 92, spin: 99, control: 88, tacky: true,
    sponge: SP.dhsBlue, colors: ['black', 'red'], weight: 50, price: 520, tag: '国手配置',
    note: '粘性面胶的顶点。发球、摆短、弧圈的旋转无人能及，但必须灌胶/灌油并主动发力。' },
  { id: 'h3-provincial', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane 3 Provincial', cn: '狂飙三 省狂',
    type: 'inv', hard: 76, hardLabel: '39 度', speed: 90, spin: 97, control: 87, tacky: true,
    sponge: SP.dhsBlue, colors: ['black', 'red'], weight: 50, price: 220, tag: '省队版',
    note: '国狂之下的省队版本，旋转略降但价格只有一半，专业队最常见的正手配置。' },
  { id: 'h3-neo', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane 3 Neo', cn: '狂飙三 普狂',
    type: 'inv', hard: 70, hardLabel: '39 度', speed: 86, spin: 93, control: 86, tacky: true,
    sponge: SP.dhs, colors: ['black', 'red'], weight: 50, price: 120, tag: '销量之王',
    note: 'Neo 预置膨胀处理，免灌胶也能打。国内最普及的正手套胶，性价比极高。' },
  { id: 'hurricane8', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane 8', cn: '狂飙 8',
    type: 'inv', hard: 66, hardLabel: '39 度', speed: 92, spin: 90, control: 86, tacky: true,
    sponge: SP.dhs, colors: ['black', 'red'], weight: 49, price: 220, tag: '',
    note: '为反手设计的粘性套胶，海绵更弹，出球比狂飙三更快，反手拉球很顶。' },
  { id: 'hurricane8-80', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane 8-80', cn: '狂飙 8-80',
    type: 'inv', hard: 60, hardLabel: '37 度', speed: 90, spin: 88, control: 88, tacky: true,
    sponge: SP.dhs, colors: ['black', 'red'], weight: 48, price: 230, tag: '',
    note: '海绵更软、更透，反手起下旋轻松，适合力量一般但想用粘性胶的球友。' },
  { id: 'skyline3', brand: 'DHS', brandCn: '红双喜', name: 'Skyline 3', cn: '天极三',
    type: 'inv', hard: 74, hardLabel: '39 度', speed: 88, spin: 94, control: 88, tacky: true,
    sponge: SP.dhs, colors: ['black', 'red'], weight: 50, price: 180, tag: '',
    note: '比狂飙三更硬的粘性胶，弧线低平、下扎明显，适合正手爆冲为主的打法。' },
  { id: 'skyline2', brand: 'DHS', brandCn: '红双喜', name: 'Skyline 2', cn: '天极二',
    type: 'inv', hard: 78, hardLabel: '39 度', speed: 90, spin: 92, control: 86, tacky: true,
    sponge: SP.dhs, colors: ['black', 'red'], weight: 50, price: 180, tag: '',
    note: '面胶更粘、海绵更硬，速度比天极三再快一点，进攻性更强。' },
  { id: 'hurricane3-50', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane 3-50', cn: '狂飙 3-50',
    type: 'inv', hard: 58, hardLabel: '37 度', speed: 88, spin: 90, control: 89, tacky: true,
    sponge: SP.dhs, colors: ['black', 'red'], weight: 48, price: 160, tag: '',
    note: '软海绵版粘性胶，一改狂飙"难打透"的印象，业余球友上手更容易。' },
  { id: 'hurricane9', brand: 'DHS', brandCn: '红双喜', name: 'Hurricane 9', cn: '狂飙 9',
    type: 'inv', hard: 64, hardLabel: '38 度', speed: 92, spin: 95, control: 88, tacky: true,
    sponge: SP.dhs, colors: ['black', 'red'], weight: 49, price: 260, tag: '新品',
    note: '新一代粘性套胶，海绵回弹明显提升，在保留旋转的同时解决了速度短板。' },

  /* ===== 亚萨卡 Yasaka ===== */
  { id: 'markv', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Mark V', cn: '马克 V',
    type: 'inv', hard: 45, hardLabel: '35°', speed: 78, spin: 82, control: 94, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 42, price: 260, tag: '传奇经典',
    note: '卖了四十多年仍在产的套胶。控制与手感的标杆，配纯木底板格外舒服。' },
  { id: 'markv-hps', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Mark V HPS', cn: '马克 V HPS',
    type: 'inv', hard: 50, hardLabel: '38°', speed: 85, spin: 85, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 44, price: 340, tag: '',
    note: 'Mark V 的加硬高速版，保留了经典手感，出球速度提升一档。' },
  { id: 'rakza7', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Rakza 7', cn: '拉卡扎 7',
    type: 'inv', hard: 52, hardLabel: '38°', speed: 88, spin: 90, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 45, price: 380, tag: '全能',
    note: '德系海绵 + 日系面胶的结合体，旋转、速度、控制三项都在水准之上。' },
  { id: 'rakza7soft', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Rakza 7 Soft', cn: '拉卡扎 7 软',
    type: 'inv', hard: 42, hardLabel: '32°', speed: 84, spin: 88, control: 92, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 43, price: 380, tag: '',
    note: '软海绵版，起下旋非常轻松，反手与入门球友的首选。' },
  { id: 'rakza9', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Rakza 9', cn: '拉卡扎 9',
    type: 'inv', hard: 56, hardLabel: '40°', speed: 93, spin: 88, control: 84, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 46, price: 400, tag: '',
    note: 'Rakza 系列中最快的一支，海绵更硬，适合近台抢攻与反手弹击。' },
  { id: 'rakzaz', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Rakza Z', cn: '拉卡扎 Z',
    type: 'inv', hard: 62, hardLabel: '42°', speed: 88, spin: 94, control: 90, tacky: true,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 48, price: 460, tag: '粘性',
    note: '微粘性面胶 + 硬海绵，旋转接近狂飙但速度更快，正手弧圈的现代选择。' },
  { id: 'pryde', brand: 'Yasaka', brandCn: '亚萨卡', name: 'Pryde', cn: '普莱德',
    type: 'inv', hard: 48, hardLabel: '36°', speed: 86, spin: 86, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 44, price: 320, tag: '',
    note: '旋转优先的均衡套胶，弧线饱满，台内控制细腻。' },

  /* ===== 挺拔 Tibhar ===== */
  { id: 'mxp', brand: 'Tibhar', brandCn: '挺拔', name: 'Evolution MX-P', cn: 'MX-P',
    type: 'inv', hard: 58, hardLabel: '47.5°', speed: 93, spin: 92, control: 86, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 47, price: 420, tag: '德系标杆',
    note: '德系套胶的销量冠军。速度与旋转兼备，正反手都能打，专业队使用率极高。' },
  { id: 'mxs', brand: 'Tibhar', brandCn: '挺拔', name: 'Evolution MX-S', cn: 'MX-S',
    type: 'inv', hard: 60, hardLabel: '48°', speed: 90, spin: 94, control: 85, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 47, price: 420, tag: '',
    note: 'MX-P 的旋转强化版，面胶更粘、海绵更硬，弧圈球质更高但需要发力。' },
  { id: 'elp', brand: 'Tibhar', brandCn: '挺拔', name: 'Evolution EL-P', cn: 'EL-P',
    type: 'inv', hard: 52, hardLabel: '45°', speed: 89, spin: 90, control: 89, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 46, price: 420, tag: '反手神器',
    note: '中等硬度，持球与出球速度平衡得极好，被公认为最佳反手套胶之一。' },
  { id: 'fxp', brand: 'Tibhar', brandCn: '挺拔', name: 'Evolution FX-P', cn: 'FX-P',
    type: 'inv', hard: 44, hardLabel: '40°', speed: 84, spin: 88, control: 92, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 44, price: 420, tag: '',
    note: '软海绵版，容易打透、容错高，反手拧拉与防守反攻都很顺手。' },
  { id: 'mxd', brand: 'Tibhar', brandCn: '挺拔', name: 'Evolution MX-D', cn: 'MX-D',
    type: 'inv', hard: 62, hardLabel: '50°', speed: 95, spin: 92, control: 84, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 48, price: 460, tag: '',
    note: '德系最硬的一档，出球极快，适合力量大、打法凶狠的选手。' },
  { id: 'k3', brand: 'Tibhar', brandCn: '挺拔', name: 'Hybrid K3', cn: '混合 K3',
    type: 'inv', hard: 64, hardLabel: '50°', speed: 92, spin: 96, control: 88, tacky: true,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 49, price: 520, tag: '粘性新品',
    note: '德系粘性套胶的代表作。既有狂飙的旋转，又有德系的海绵弹性，正手极强。' },
  { id: 'k2', brand: 'Tibhar', brandCn: '挺拔', name: 'Hybrid K2', cn: '混合 K2',
    type: 'inv', hard: 60, hardLabel: '48°', speed: 90, spin: 94, control: 89, tacky: true,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 48, price: 480, tag: '',
    note: 'K3 的稍软版本，更好上手，保留了粘性面胶的旋转优势。' },
  { id: 'aurus', brand: 'Tibhar', brandCn: '挺拔', name: 'Aurus Select', cn: '奥洛斯',
    type: 'inv', hard: 50, hardLabel: '43°', speed: 88, spin: 88, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 45, price: 340, tag: '',
    note: '面向进阶球友的均衡套胶，旋转好、手感柔和，配纤维板很搭。' },

  /* ===== 多尼克 Donic ===== */
  { id: 'bluefire-m1', brand: 'Donic', brandCn: '多尼克', name: 'Bluefire M1', cn: '蓝火 M1',
    type: 'inv', hard: 60, hardLabel: '47.5°', speed: 94, spin: 92, control: 82, tacky: false,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 47, price: 380, tag: '',
    note: '蓝色海绵的开创者。出球快、弧线低，中远台对拉的力量表现出色。' },
  { id: 'bluefire-m2', brand: 'Donic', brandCn: '多尼克', name: 'Bluefire M2', cn: '蓝火 M2',
    type: 'inv', hard: 54, hardLabel: '45°', speed: 91, spin: 91, control: 84, tacky: false,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 46, price: 380, tag: '',
    note: 'M1 的稍软版，速度与控制的平衡更好，正反手通用的万金油。' },
  { id: 'bluefire-m3', brand: 'Donic', brandCn: '多尼克', name: 'Bluefire M3', cn: '蓝火 M3',
    type: 'inv', hard: 46, hardLabel: '40°', speed: 87, spin: 90, control: 88, tacky: false,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 44, price: 380, tag: '',
    note: '软海绵，吃球深、易起下旋，反手和入门球友都很友好。' },
  { id: 'bluestorm-z1', brand: 'Donic', brandCn: '多尼克', name: 'BlueStorm Z1', cn: '蓝风暴 Z1',
    type: 'inv', hard: 62, hardLabel: '50°', speed: 95, spin: 93, control: 83, tacky: false,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 48, price: 460, tag: '',
    note: '蓝火之后的换代产品，海绵内能更高，出球速度与旋转同时提升。' },
  { id: 'bluegrip-c1', brand: 'Donic', brandCn: '多尼克', name: 'BlueGrip C1', cn: '蓝握 C1',
    type: 'inv', hard: 64, hardLabel: '50°', speed: 90, spin: 96, control: 88, tacky: true,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 49, price: 520, tag: '粘性',
    note: '德系粘性套胶，旋转接近狂飙但速度更快，是"免灌胶狂飙"的有力替代。' },
  { id: 'bluegrip-s1', brand: 'Donic', brandCn: '多尼克', name: 'BlueGrip S1', cn: '蓝握 S1',
    type: 'inv', hard: 56, hardLabel: '45°', speed: 88, spin: 92, control: 90, tacky: true,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 47, price: 480, tag: '',
    note: '微粘面胶 + 中等海绵，旋转好且容易上手，反手也能驾驭。' },
  { id: 'acuda-s1', brand: 'Donic', brandCn: '多尼克', name: 'Acuda S1', cn: '阿库达 S1',
    type: 'inv', hard: 52, hardLabel: '45°', speed: 90, spin: 88, control: 86, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 45, price: 300, tag: '性价比',
    note: '德系套胶中的高性价比之选，速度不错、手感通透，练球与比赛都能用。' },

  /* ===== 骄猛 Xiom ===== */
  { id: 'vega-pro', brand: 'Xiom', brandCn: '骄猛', name: 'Vega Pro', cn: '维加 专业',
    type: 'inv', hard: 56, hardLabel: '47.5°', speed: 91, spin: 90, control: 86, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 46, price: 340, tag: '',
    note: '韩国队的常用配置。旋转与速度均衡，海绵回弹迅速。' },
  { id: 'vega-europe', brand: 'Xiom', brandCn: '骄猛', name: 'Vega Europe', cn: '维加 欧洲',
    type: 'inv', hard: 46, hardLabel: '42.5°', speed: 85, spin: 88, control: 92, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 44, price: 340, tag: '反手推荐',
    note: '柔和易控，起下旋非常轻松，被认为是反手入门到进阶的最佳选择之一。' },
  { id: 'vega-asia', brand: 'Xiom', brandCn: '骄猛', name: 'Vega Asia', cn: '维加 亚洲',
    type: 'inv', hard: 52, hardLabel: '45°', speed: 89, spin: 89, control: 89, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 45, price: 340, tag: '',
    note: '介于欧洲版与专业版之间，为亚洲选手的快速衔接打法调校。' },
  { id: 'omega7-pro', brand: 'Xiom', brandCn: '骄猛', name: 'Omega VII Pro', cn: '欧米茄 7 专业',
    type: 'inv', hard: 60, hardLabel: '50°', speed: 95, spin: 94, control: 86, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 48, price: 480, tag: '旗舰',
    note: '骄猛的顶级型号，内能海绵弹性极强，中远台对拉的质量非常高。' },
  { id: 'omega7-asia', brand: 'Xiom', brandCn: '骄猛', name: 'Omega VII Asia', cn: '欧米茄 7 亚洲',
    type: 'inv', hard: 57, hardLabel: '48°', speed: 93, spin: 93, control: 87, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 47, price: 480, tag: '',
    note: '为近台快节奏调校，弧线更低平，衔接速度快。' },
  { id: 'jekyll-v475', brand: 'Xiom', brandCn: '骄猛', name: 'Jekyll & Hyde V47.5', cn: '化身博士 V47.5',
    type: 'inv', hard: 58, hardLabel: '47.5°', speed: 91, spin: 93, control: 87, tacky: true,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 47, price: 420, tag: '粘性',
    note: '微粘面胶搭配高弹海绵，旋转出色且不用灌胶，正手弧圈很稳。' },

  /* ===== 优拉 Joola ===== */
  { id: 'rhyzen-fire', brand: 'Joola', brandCn: '优拉', name: 'Rhyzen Fire', cn: '雷神 火',
    type: 'inv', hard: 58, hardLabel: '48°', speed: 94, spin: 92, control: 84, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 47, price: 420, tag: '',
    note: '优拉的进攻型旗舰，海绵内能强，出球速度快、弧线低。' },
  { id: 'rhyzen-ice', brand: 'Joola', brandCn: '优拉', name: 'Rhyzen Ice', cn: '雷神 冰',
    type: 'inv', hard: 50, hardLabel: '43°', speed: 88, spin: 90, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 45, price: 420, tag: '',
    note: '偏控制的版本，持球时间长，落点控制精准。' },
  { id: 'dynaryz-agr', brand: 'Joola', brandCn: '优拉', name: 'Dynaryz AGR', cn: '迪纳瑞 AGR',
    type: 'inv', hard: 60, hardLabel: '50°', speed: 93, spin: 95, control: 86, tacky: true,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 48, price: 500, tag: '粘性',
    note: '粘性面胶 + 高弹海绵，旋转强烈且速度不慢，正手爆冲威力大。' },
  { id: 'dynaryz-acc', brand: 'Joola', brandCn: '优拉', name: 'Dynaryz ACC', cn: '迪纳瑞 ACC',
    type: 'inv', hard: 57, hardLabel: '47.5°', speed: 94, spin: 93, control: 84, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 47, price: 480, tag: '',
    note: '速度优先的型号，脱板快，适合近台快攻与反手弹击。' },

  /* ===== 斯帝卡 Stiga ===== */
  { id: 'mantra-m', brand: 'Stiga', brandCn: '斯帝卡', name: 'Mantra M', cn: '曼陀罗 M',
    type: 'inv', hard: 54, hardLabel: '45°', speed: 90, spin: 90, control: 88, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 46, price: 400, tag: '',
    note: '斯帝卡的均衡型套胶，配自家底板手感协调，旋转与速度都不错。' },
  { id: 'mantra-h', brand: 'Stiga', brandCn: '斯帝卡', name: 'Mantra H', cn: '曼陀罗 H',
    type: 'inv', hard: 60, hardLabel: '50°', speed: 94, spin: 89, control: 84, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 47, price: 400, tag: '',
    note: '硬海绵版本，出球更快，适合力量充足的进攻型选手。' },
  { id: 'dna-pro-m', brand: 'Stiga', brandCn: '斯帝卡', name: 'DNA Pro M', cn: 'DNA 专业 M',
    type: 'inv', hard: 56, hardLabel: '47.5°', speed: 92, spin: 92, control: 87, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 46, price: 460, tag: '',
    note: '新一代内能套胶，海绵回弹快，弧圈与快攻兼顾。' },
  { id: 'dna-platinum', brand: 'Stiga', brandCn: '斯帝卡', name: 'DNA Platinum M', cn: 'DNA 白金 M',
    type: 'inv', hard: 58, hardLabel: '50°', speed: 94, spin: 94, control: 86, tacky: false,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 47, price: 560, tag: '旗舰',
    note: '斯帝卡的顶级套胶，面胶摩擦系数高，旋转与速度同时拉满。' },

  /* ===== 尼塔库 Nittaku ===== */
  { id: 'fastarc-g1', brand: 'Nittaku', brandCn: '尼塔库', name: 'Fastarc G-1', cn: '法斯塔 G-1',
    type: 'inv', hard: 56, hardLabel: '47.5°', speed: 91, spin: 93, control: 88, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 46, price: 460, tag: '正手名胶',
    note: '日系套胶的常青树。旋转强、弧线好，正手弧圈的稳定性极高。' },
  { id: 'fastarc-c1', brand: 'Nittaku', brandCn: '尼塔库', name: 'Fastarc C-1', cn: '法斯塔 C-1',
    type: 'inv', hard: 50, hardLabel: '43°', speed: 88, spin: 91, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 45, price: 460, tag: '',
    note: 'G-1 的稍软版本，持球更好，反手使用非常舒服。' },
  { id: 'fastarc-s1', brand: 'Nittaku', brandCn: '尼塔库', name: 'Fastarc S-1', cn: '法斯塔 S-1',
    type: 'inv', hard: 44, hardLabel: '38°', speed: 85, spin: 88, control: 92, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 44, price: 460, tag: '',
    note: '软海绵版本，容错极高，适合以稳定和落点为主的打法。' },
  { id: 'moristo-sp', brand: 'Nittaku', brandCn: '尼塔库', name: 'Moristo SP', cn: '莫里斯托 SP',
    type: 'mp', hard: 48, hardLabel: '40°', speed: 88, spin: 72, control: 88, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 40, price: 420, tag: '',
    note: '生胶。颗粒横向排列，回球下沉明显，是生胶打法的主流选择。' },
  { id: 'hammond-fa', brand: 'Nittaku', brandCn: '尼塔库', name: 'Hammond FA', cn: '哈蒙德 FA',
    type: 'inv', hard: 48, hardLabel: '40°', speed: 89, spin: 87, control: 89, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 44, price: 400, tag: '',
    note: '速度快、手感脆，近台借力与快带的反馈非常直接。' },

  /* ===== 维克塔斯 Victas ===== */
  { id: 'v15-extra', brand: 'Victas', brandCn: '维克塔斯', name: 'V > 15 Extra', cn: 'V15 特厚',
    type: 'inv', hard: 58, hardLabel: '47.5°', speed: 92, spin: 92, control: 88, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 46, price: 460, tag: '',
    note: '日系内能套胶，海绵支撑好、旋转强，中远台表现稳定。' },
  { id: 'v20-extra', brand: 'Victas', brandCn: '维克塔斯', name: 'V > 20 Extra', cn: 'V20 特厚',
    type: 'inv', hard: 62, hardLabel: '50°', speed: 89, spin: 91, control: 89, tacky: true,
    sponge: SP.esnBlue, colors: ['black', 'red'], weight: 47, price: 500, tag: '粘性',
    note: '微粘性面胶，旋转出色、弧线饱满，是日系粘性胶的代表。' },
  { id: 'spectol-s1', brand: 'Victas', brandCn: '维克塔斯', name: 'Spectol S1', cn: '斯派克 S1',
    type: 'sp', hard: 50, hardLabel: '42°', speed: 90, spin: 74, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 41, price: 420, tag: '正胶标杆',
    note: '正胶的经典型号。速度快、下沉明显，近台快攻与快带极具威胁。' },
  { id: 'v401', brand: 'Victas', brandCn: '维克塔斯', name: 'V > 401', cn: 'V401',
    type: 'mp', hard: 46, hardLabel: '40°', speed: 86, spin: 70, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 40, price: 440, tag: '',
    note: '生胶。颗粒设计兼顾速度与怪异度，接发球和相持中变化丰富。' },
  { id: 'curl-p1v', brand: 'Victas', brandCn: '维克塔斯', name: 'Curl P1V', cn: '卷曲 P1V',
    type: 'lp', hard: 40, hardLabel: '32°', speed: 56, spin: 64, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 34, price: 480, tag: '长胶经典',
    note: '长胶中的控制之王。削球稳定性极高，世界顶级削球手的主流选择。' },
  { id: 'curl-p4v', brand: 'Victas', brandCn: '维克塔斯', name: 'Curl P4V', cn: '卷曲 P4V',
    type: 'lp', hard: 38, hardLabel: '30°', speed: 58, spin: 60, control: 88, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 33, price: 480, tag: '',
    note: '颗粒更长的长胶，回球更飘忽、反旋转更强，但控制难度也更高。' },

  /* ===== 友谊 729 ===== */
  { id: 'focus3-snipe', brand: 'Friendship', brandCn: '友谊 729', name: '729 Focus III Snipe', cn: '焦点三 狙击',
    type: 'inv', hard: 50, hardLabel: '42°', speed: 86, spin: 88, control: 90, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 44, price: 90, tag: '国产性价比',
    note: '国产内能套胶的进步之作，旋转和速度都够用，价格只有进口胶的三分之一。' },
  { id: '729-08es', brand: 'Friendship', brandCn: '友谊 729', name: '729-08 ES', cn: '729-08 ES',
    type: 'inv', hard: 54, hardLabel: '45°', speed: 88, spin: 86, control: 88, tacky: false,
    sponge: SP.esn, colors: ['black', 'red'], weight: 45, price: 70, tag: '',
    note: '经典国产品牌的升级版，海绵弹性提升明显，正手快攻很实惠。' },
  { id: 'battle2', brand: 'Friendship', brandCn: '友谊 729', name: '729 Battle II', cn: '729 战魂二',
    type: 'inv', hard: 70, hardLabel: '39 度', speed: 88, spin: 90, control: 88, tacky: true,
    sponge: SP.dhs, colors: ['black', 'red'], weight: 48, price: 180, tag: '国产粘性',
    note: '国产粘性套胶的性价比代表，旋转接近狂飙，价格便宜很多。' },
  { id: '729-superfx', brand: 'Friendship', brandCn: '友谊 729', name: '729 Super FX', cn: '729 超级 FX',
    type: 'inv', hard: 46, hardLabel: '40°', speed: 80, spin: 84, control: 92, tacky: true,
    sponge: SP.esn, colors: ['black', 'red'], weight: 43, price: 45, tag: '入门经典',
    note: '几代中国球友的启蒙胶皮。微粘、好控，配五夹纯木练基本功非常合适。' },
  { id: '729-tianyi', brand: 'Friendship', brandCn: '友谊 729', name: '729 Tianyi', cn: '729 天翼',
    type: 'inv', hard: 48, hardLabel: '41°', speed: 82, spin: 86, control: 91, tacky: true,
    sponge: SP.esn, colors: ['black', 'red'], weight: 43, price: 60, tag: '',
    note: '轻量化设计的国产粘性胶，配重友好，适合直板横打。' },
];

/**
 * 各型号手柄的饰条布局与标牌样式。
 *
 * 说明：手柄是木片叠压出来的，所以平面看得到 1~3 条纵向饰条。各家手柄的典型
 * 做法不同 —— 蝴蝶是「圆金属标牌 + 一到两条对比饰条」，斯帝卡多为素木加一道
 * 细线，红双喜常带彩色条。这里按这些品牌特征归纳，**属于风格化还原，
 * 不是逐型号对着实物描的**；颜色则取自每块底板自己的柄色。
 *
 * layout: center 居中一条 / twin 两侧对称 / edge 靠边 / trio 不对称三条 / line 素木细线
 * lens:   round 圆标牌 / oval 椭圆 / none 无
 */
export const HANDLE_STYLE = {
  // 蝴蝶 —— 圆标牌，饰条偏简洁
  viscaria:        { layout: 'center', lens: 'round' },
  'boll-alc':      { layout: 'twin',   lens: 'round' },
  'boll-spirit':   { layout: 'twin',   lens: 'round' },
  'boll-zlc':      { layout: 'edge',   lens: 'round' },
  'boll-zlf':      { layout: 'edge',   lens: 'round' },
  'zjk-alc':       { layout: 'twin',   lens: 'round' },
  'zjk-zlc':       { layout: 'center', lens: 'round' },
  'zjk-szlc':      { layout: 'center', lens: 'oval'  },
  'fzd-alc':       { layout: 'twin',   lens: 'round' },
  'fzd-zlc':       { layout: 'edge',   lens: 'round' },
  'harimoto-alc':  { layout: 'trio',   lens: 'oval'  },
  'harimoto-inner':{ layout: 'trio',   lens: 'oval'  },
  'harimoto-zlc':  { layout: 'edge',   lens: 'oval'  },
  'innerforce-alc':{ layout: 'center', lens: 'round' },
  'innerforce-zlc':{ layout: 'center', lens: 'round' },
  korbel:          { layout: 'line',   lens: 'round' },
  'korbel-sk7':    { layout: 'line',   lens: 'round' },
  primorac:        { layout: 'line',   lens: 'round' },
  maze:            { layout: 'twin',   lens: 'round' },
  'schlager-carbon': { layout: 'center', lens: 'oval' },
  amultart:        { layout: 'trio',   lens: 'oval'  },
  photino:         { layout: 'edge',   lens: 'round' },
  'ovtcharov-tc':  { layout: 'twin',   lens: 'round' },
  'kong-linghui':  { layout: 'line',   lens: 'round' },
  'sk7-classic':   { layout: 'line',   lens: 'round' },
  'hadraw-5':      { layout: 'line',   lens: 'round' },
  'hadraw-vr':     { layout: 'twin',   lens: 'round' },

  // 红双喜 —— 素木为主，常带一条彩色条，无蝴蝶式标牌
  hl5:             { layout: 'center', lens: 'none' },
  hl5x:            { layout: 'center', lens: 'none' },
  hl3:             { layout: 'twin',   lens: 'none' },
  'fangbo-carbon': { layout: 'trio',   lens: 'none' },
  hao2:            { layout: 'line',   lens: 'none' },

  // 斯帝卡 —— 素木 + 细线，无标牌
  ebenholz7:       { layout: 'line',   lens: 'none' },
  rosewood7:       { layout: 'line',   lens: 'none' },
  clipper:         { layout: 'line',   lens: 'none' },
  carbo76:         { layout: 'twin',   lens: 'none' },

  // 尼塔库 / 亚萨卡 / 挺拔
  acoustic:        { layout: 'line',   lens: 'none' },
  violin:          { layout: 'line',   lens: 'none' },
  latika:          { layout: 'line',   lens: 'none' },
  'malin-carbon':  { layout: 'center', lens: 'none' },
  yeo:             { layout: 'twin',   lens: 'none' },
  'force-pro':     { layout: 'center', lens: 'none' },
  'stratus-pw':    { layout: 'twin',   lens: 'none' },
};

export const BRANDS = [...new Set(BLADES.map(b => b.brand))];
export const RUBBER_BRANDS = [...new Set(RUBBERS.map(r => r.brand))];
